# Generated by Django 5.1.5 on 2025-01-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kurs tavsifi')),
                ('category', models.CharField(max_length=100, verbose_name='Kurs kategoriyasi')),
                ('duration', models.IntegerField(verbose_name='Kurs davomiyligi')),
                ('level', models.CharField(choices=[('Boshlang‘ich', 'Boshlang‘ich'), ('O‘rta', 'O‘rta'), ('Yuqori', 'Yuqori')], max_length=50, verbose_name='Kurs darajasi')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Kurs narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video tavsifi')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Video fayli')),
                ('section', models.CharField(max_length=100, verbose_name='Video bo‘limi')),
                ('section_order', models.IntegerField(verbose_name='Bo‘lim tartibi')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Video davomiyligi')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Video tili')),
                ('quality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Video sifati')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video mini-rasm')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Video ko‘rinishi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.course', verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['section_order', 'title'],
            },
        ),
    ]
