# Generated by Django 5.1.6 on 2025-02-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('password', models.CharField(default='NavduMurojat2024*', max_length=100)),
            ],
        ),
    ]
